version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    container_name: tools-blogger-nginx
    volumes:
      - /data/tools.blogger.pe.kr:/var/www/html
    environment:
      - TZ=Asia/Seoul
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - reverse_proxy
      - internal_network
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./php-fpm
    container_name: tools-blogger-php-fpm
    volumes:
      - /data/tools.blogger.pe.kr:/var/www/html
      - /data/tools.blogger.pe.kr/logs:/var/www/html/logs
    environment:
      - TZ=Asia/Seoul
    restart: unless-stopped
    networks:
      - internal_network

networks:
  reverse_proxy:
    external: true
  internal_network:
    driver: bridge